version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.1
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "test:1:1"

  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:21.1.1
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - "9090:8080"
      command:
        - "start-dev"

  postgres:
    image: postgres:16.0
    hostname: 6ebf8cc8f5d6
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: ticket
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/data